Update kubeovn-adm

diff --git a/src/kubeovn-adm b/src/kubeovn-adm
--- a/src/kubeovn-adm
+++ b/src/kubeovn-adm
@@ -157,7 +157,7 @@ function create-br-c-br()
 
 ###########################################################
 ##
-##  
+##  L2 bridge
 ##
 ##########################################################
 
@@ -294,9 +294,83 @@ function delete-bridge()
 
 }
 
+function create-fip()
+{
+  name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
+  ip=$(echo $* | awk -F"--ip" '{print$2}' | awk '{print$1}')
+
+  if [[ -z $1 || -z $name || -z $ip || $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--name      \tPhysical NIC name" >&2
+    echo -e "--ip        \tFloating IP" >&2
+    exit 1
+  fi
+
+  ne=$(ip a | grep $name)
+  if [[ -z $ne ]]
+  then
+    echo "Physical NIC not exist" >&2
+    exit 1
+  fi
+
+  ie=$(ip a | grep $ip)
+  if [[ -n $ie ]]
+  then
+    echo "IP exist" >&2
+    exit 1
+  fi 
+
+  for i in `seq 1 1000`
+  do
+    fname=$name":"$i
+    if [[ -f /etc/sysconfig/network-scripts/ifcfg-$fname ]]
+    then
+      continue
+    fi
+    mask=$(ip a | grep -A 1 $name | grep inet | awk 'NR==1' |awk '{print$2}' | awk -F"/" '{print$2}')
+    rm -rf /etc/sysconfig/network-scripts/ifcfg-$fname
+    echo "DEVICE=$fname" >> /etc/sysconfig/network-scripts/ifcfg-$fname
+    echo "BOOTPROTO=static" >> /etc/sysconfig/network-scripts/ifcfg-$fname
+    echo "ONBOOT=yes" >> /etc/sysconfig/network-scripts/ifcfg-$fname
+    echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-$fname
+    echo "IPADDR=$ip" >> /etc/sysconfig/network-scripts/ifcfg-$fname
+    echo "PREFIX=$mask" >> /etc/sysconfig/network-scripts/ifcfg-$fname
+    ifup $fname
+    exit 0
+  done
+
+  echo "too much floating IPs" >&2
+  exit 1   
+
+}
+
+
+function delete-fip()
+{
+  ip=$(echo $* | awk -F"--ip" '{print$2}' | awk '{print$1}')
+  fname=$(ip a | grep $ip | awk '{print$8}')
+
+  if [[ -z $1 || -z $ip || $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--ip        \tFloating IP" >&2
+    exit 1
+  fi
+
+  if [[ -z $fname ]]
+  then
+    echo "wrong IP, cannot find a NIC with the IP" >&2
+    exit 1
+  fi
+
+  ifconfig $fname down
+  rm -rf /etc/sysconfig/network-scripts/ifcfg-$fname
+}
+
 ###########################################################
 ##
-##  l2
+##  l3 switch
 ##
 ###########################################################
 
@@ -562,81 +636,6 @@ function delport-vxlan()
   
   ovs-vsctl remove port $name tag $vxlan
   ovs-vsctl set interface $name type=internal
-}
-
-
-function create-fip()
-{
-  name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
-  ip=$(echo $* | awk -F"--ip" '{print$2}' | awk '{print$1}')
-
-  if [[ -z $1 || -z $name || -z $ip || $2 == "--help" ]]
-  then
-    cmddesc
-    echo -e "--name      \tPhysical NIC name" >&2
-    echo -e "--ip        \tFloating IP" >&2
-    exit 1
-  fi
-
-  ne=$(ip a | grep $name)
-  if [[ -z $ne ]]
-  then
-    echo "Physical NIC not exist" >&2
-    exit 1
-  fi
-
-  ie=$(ip a | grep $ip)
-  if [[ -n $ie ]]
-  then
-    echo "IP exist" >&2
-    exit 1
-  fi 
-
-  for i in `seq 1 1000`
-  do
-    fname=$name":"$i
-    if [[ -f /etc/sysconfig/network-scripts/ifcfg-$fname ]]
-    then
-      continue
-    fi
-    mask=$(ip a | grep -A 1 $name | grep inet | awk 'NR==1' |awk '{print$2}' | awk -F"/" '{print$2}')
-    rm -rf /etc/sysconfig/network-scripts/ifcfg-$fname
-    echo "DEVICE=$fname" >> /etc/sysconfig/network-scripts/ifcfg-$fname
-    echo "BOOTPROTO=static" >> /etc/sysconfig/network-scripts/ifcfg-$fname
-    echo "ONBOOT=yes" >> /etc/sysconfig/network-scripts/ifcfg-$fname
-    echo "NM_CONTROLLED=no" >> /etc/sysconfig/network-scripts/ifcfg-$fname
-    echo "IPADDR=$ip" >> /etc/sysconfig/network-scripts/ifcfg-$fname
-    echo "PREFIX=$mask" >> /etc/sysconfig/network-scripts/ifcfg-$fname
-    ifup $fname
-    exit 0
-  done
-
-  echo "too much floating IPs" >&2
-  exit 1   
-
-}
-
-
-function delete-fip()
-{
-  ip=$(echo $* | awk -F"--ip" '{print$2}' | awk '{print$1}')
-  fname=$(ip a | grep $ip | awk '{print$8}')
-
-  if [[ -z $1 || -z $ip || $2 == "--help" ]]
-  then
-    cmddesc
-    echo -e "--ip        \tFloating IP" >&2
-    exit 1
-  fi
-
-  if [[ -z $fname ]]
-  then
-    echo "wrong IP, cannot find a NIC with the IP" >&2
-    exit 1
-  fi
-
-  ifconfig $fname down
-  rm -rf /etc/sysconfig/network-scripts/ifcfg-$fname
 }
 
 function bind-fip()
