update

diff --git a/src/kubeovn-adm b/src/kubeovn-adm
--- a/src/kubeovn-adm
+++ b/src/kubeovn-adm
@@ -862,6 +862,94 @@ function delete-acl()
 }
 
 
+function bind-fip()
+{
+  switch=$(echo $* | awk -F"--swName" '{print$2}' | awk '{print$1}')
+  bridge=$(echo $* | awk -F"--bridge" '{print$2}' | awk '{print$1}')
+  vmmac=$(echo $* | awk -F"--vmmac" '{print$2}' | awk '{print$1}')
+  fip=$(echo $* | awk -F"--fip" '{print$2}' | awk '{print$1}')
+ 
+  if [[ -z $1 || -z $switch || -z $bridge || -z $vmmac || -z $fip || -z $(echo $fip | grep "/") || $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--swName  \tswitch name" >&2
+    echo -e "--bridge  \tbridge" >&2
+    echo -e "--vmmac   \tvm mac" >&2
+    echo -e "--fip     \tflating ip and mask, for example, 192.168.1.1/24" >&2
+    exit 1
+  fi
+
+  checkOVSStatus
+
+  res=$(ovs-vsctl list-br | grep $bridge)
+  if [[ -z $res ]]
+  then
+    echo -e "cannot find bridge" >&2
+    exit 1
+  fi
+  
+  vmip=$($NB_CMD list logical_switch_port  | grep "$vmmac" | awk -F"\"" '{print$2}' | awk '{print$2}')
+
+  router=$switch"-router"
+  fport="public-"${vmmac//:/}"-port"
+  ip=$(echo $fip | awk -F"/" '{print$1}')
+  rmk=$(echo $fip | awk -F"/" '{print$2}')
+  #pip=$(echo $ip | awk -F"." '{print$1"."$2"."$3}')".250"
+  imac=$(printf '00:60:2F:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
+  
+  #$NB_CMD lrp-add $router $fport  $imac $pip"/"$rmk
+  $NB_CMD lrp-add $router $fport  $imac $ip"/"$rmk
+  $NB_CMD lrp-set-gateway-chassis $fport $($SB_CMD show | grep -B 3 "$THISIP" | grep Chassis | awk -F"\"" '{print$2}')
+
+  pswn="public-"${vmmac//:/}"-"$(hostname)
+  
+  $NB_CMD ls-add $pswn
+  $NB_CMD lsp-add $pswn "from-"$fport
+  $NB_CMD lsp-set-type "from-"$fport router
+  $NB_CMD lsp-set-addresses "from-"$fport $imac
+  $NB_CMD lsp-set-options "from-"$fport router-port=$fport
+  
+  $NB_CMD lsp-add $pswn "to-"$pswn"-localnet"
+  $NB_CMD lsp-set-addresses "to-"$pswn"-localnet" unknown
+  $NB_CMD lsp-set-type "to-"$pswn"-localnet" localnet
+  $NB_CMD lsp-set-options "to-"$pswn"-localnet" network_name=$pswn
+  
+  ovs-vsctl set Open_vSwitch . external-ids:ovn-bridge-mappings=$pswn:$bridge
+
+  $NB_CMD lr-nat-add $router dnat_and_snat $ip $vmip
+  #$NB_CMD lr-nat-add $router dnat_and_snat $pip $vmip 
+  
+}
+
+function unbind-fip()
+{
+  switch=$(echo $* | awk -F"--swName" '{print$2}' | awk '{print$1}')
+  vmmac=$(echo $* | awk -F"--vmmac" '{print$2}' | awk '{print$1}')
+  fip=$(echo $* | awk -F"--fip" '{print$2}' | awk '{print$1}')
+
+  if [[ -z $1 || -z $switch || -z $vmmac || -z $fip || -n $(echo $fip | grep "/") ||  $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--swName  \tswitch name" >&2
+    echo -e "--vmmac   \tvm mac" >&2
+    echo -e "--fip     \tfip" >&2
+    exit 1
+  fi
+
+  checkOVSStatus
+  
+  pswn="public-"${vmmac//:/}"-"$(hostname)
+  $NB_CMD ls-del $pswn
+
+  router=$switch"-router"
+  fport="public-"${vmmac//:/}"-port"
+  $NB_CMD lrp-del $fport
+  #pip=$(echo $ip | awk -F"." '{print$1"."$2"."$3}')".250"
+  $NB_CMD lr-nat-del $router dnat_and_snat $fip
+  #$NB_CMD lr-nat-del $router dnat_and_snat $pip
+}
+
+
 ###########################################################
 ##
 ##  QoS
