update

diff --git a/src/ovn-emulator b/src/ovn-emulator
--- a/src/ovn-emulator
+++ b/src/ovn-emulator
@@ -331,31 +331,36 @@ function delbridge-vlan()
 
 function create-switch()
 {
+  function create-switch()
+{
   name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
   subn=$(echo $* | awk -F"--subnet" '{print$2}' | awk '{print$1}')
   gway=$(echo $* | awk -F"--gateway" '{print$2}' | awk '{print$1}')
+  dhcp=$(echo $* | awk -F"--dhcp" '{print$2}' | awk '{print$1}')
   imtu=$(echo $* | awk -F"--mtu" '{print$2}' | awk '{print$1}')
   excl=$(echo $* | awk -F"--excludeIPs" '{print$2}' | awk '{print$1}')
   dnss=$(echo $* | awk -F"--dnsServer" '{print$2}' | awk '{print$1}')
   
-  if [[ -z $1 || -z $name || $2 == "--help" ]]
+  if [[ -z $1 || -z $name || -z $subn || $2 == "--help" ]]
   then
     cmddesc
     echo -e "--name       \tswitch name" >&2
-    echo -e "--subnet     \toptinal, IP range. for example, 192.168.1.0/24"  >&2
+    echo -e "--subnet     \tIP range. for example, 192.168.1.0/24"  >&2
     echo -e "--gateway    \toptinal, gateway.  for example, 192.168.1.1"  >&2
     echo -e "--mtu        \toptinal, mtu.  for example, 1480"  >&2
+    echo -e "--dhcp       \toptinal, dhcp"  >&2
     echo -e "--excludeIPs \toptinal, excludeIPs.  192.168.1.1,192.168.1.10..192.168.1.100"  >&2
     echo -e "--dnsServer  \toptinal, dnsServer.  192.168.1.1"  >&2
     exit 1
   fi
 
-  ## check 
-  
-  checkOVSStatus
-  checkDuplicate $name
+  sid=$($NB_CMD ls-list | grep "($name)" | awk '{print$1}')
+  if [[ -n $sid ]]
+  then
+    echo "cannot connect the master or the switch name exists" >&2
+    exit 1
+  fi
  
-  ## create and config
   $NB_CMD ls-add $name
 
   if [[ -n $excl ]]
@@ -364,43 +369,59 @@ function create-switch()
     $NB_CMD set Logical_Switch $name other_config:exclude_ips="$nexcl"
   fi
  
-  rip=$(echo $subn | awk -F"." '{print$1"."$2"."$3}')".1"
-  if [[ -n $gway ]]
+  if [[ -n $subn ]]
   then
-    rip=$gway
-  fi
+  
+    mtu="1500"
+    if [[ -n $imtu ]]
+    then
+      mtu=$imtu
+    fi
+ 
+    if [[ -n $dhcp ]]
+    then
+      router=$name"-router"
+      rport=$name"-router-port"
+      rmac=$(printf '00:60:2F:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
+ 
+      $NB_CMD lr-add $router
+	  $NB_CMD set Logical_router $router options:chassis=$($SB_CMD show | grep -B 3 "$THISIP" | grep Chassis | awk -F"\"" '{print$2}')
+      rmk=$(echo $subn | awk -F"/" '{print$2}')
+      $NB_CMD lrp-add $router $rport $rmac $dhcp"/"$rmk
+  
+      mport="mapping-to-"$router
+      $NB_CMD lsp-add $name $mport
+      $NB_CMD lsp-set-type $mport router
+      $NB_CMD lsp-set-addresses $mport $rmac
+      $NB_CMD lsp-set-options $mport router-port=$rport
+  
+      sport='to-'$rport'-'$(hostname)'-localnet'
+      $NB_CMD lsp-add $name $sport
+      $NB_CMD lsp-set-addresses $sport unknown
+      $NB_CMD lsp-set-type $sport localnet
+      pswn=${rmac//:/}"-"$sport
+      
+      $NB_CMD lsp-set-options $sport network_name=$pswn
+ 
+      eids=$(ovs-vsctl list Open_vSwitch | grep external_ids | awk -F"ovn-bridge-mappings=\"" '{print$2}' | awk -F"\"" '{print$1}')
    
-  router=$name"-router"
-  rport=$name"-router-port"
-  rmac=$(printf '00:60:2F:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
-  rmk=$(echo $subn | awk -F"/" '{print$2}')
-  
-  $NB_CMD lr-add $router
-  $NB_CMD lrp-add $router $rport $rmac $rip"/"$rmk
-  
-  
-  
-  sport='to-'$rport
-  $NB_CMD lsp-add $name $sport
-  $NB_CMD lsp-set-type $sport router
-  $NB_CMD lsp-set-addresses $sport $rmac
-  $NB_CMD lsp-set-options $sport router-port=$rport
+      if [[ -z $eids ]] 
+      then
+        ovs-vsctl set Open_vSwitch . external-ids:ovn-bridge-mappings=$pswn:$bridge
+      else
+        ovs-vsctl set Open_vSwitch . external-ids:ovn-bridge-mappings=$pswn:$bridge,$eids
+      fi
 
+      if [[ -z $dnss ]]
+      then
+        did=$($NB_CMD create DHCP_Options cidr=$subn options="\"server_id\"=\"$dhcp\" \"server_mac\"=\"$rmac\" \"lease_time\"=\"3600\" \"router\"=\"$gway\" \"mtu\"=\"$mtu\"")
+      else
+        did=$($NB_CMD create DHCP_Options cidr=$subn options="\"server_id\"=\"$dhcp\" \"server_mac\"=\"$rmac\" \"lease_time\"=\"3600\" \"router\"=\"$gway\" \"mtu\"=\"$mtu\" \"dns_server\"=\"$dnss\"")
+      fi
 
-  mtu="1500"
-  if [[ -n $imtu ]]
-  then
-    mtu=$imtu
+      $NB_CMD lsp-add $name "dhcpv4id-$name-"$did
+      fi
   fi
-
-  if [[ -z $dnss ]]
-  then
-    did=$($NB_CMD create DHCP_Options cidr=$subn options="\"server_id\"=\"$rip\" \"server_mac\"=\"$rmac\" \"lease_time\"=\"3600\" \"router\"=\"$rip\" \"mtu\"=\"$mtu\"")
-  else
-    did=$($NB_CMD create DHCP_Options cidr=$subn options="\"server_id\"=\"$rip\" \"server_mac\"=\"$rmac\" \"lease_time\"=\"3600\" \"router\"=\"$rip\" \"mtu\"=\"$mtu\" \"dns_server\"=\"$dnss\"")
-  fi
-
-  $NB_CMD lsp-add $name "dhcpv4id-$name-"$did
 
 }
 
@@ -481,11 +502,13 @@ function modify-switch()
 function delete-switch()
 {
   name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
+  bridge=$(echo $* | awk -F"--bridge" '{print$2}' | awk '{print$1}')
   
   if [[ -z $1 || -z $name || $2 == "--help" ]]
   then
     cmddesc
     echo -e "--name  \tswitch name" >&2
+	echo -e "--bridge  \tbridge name" >&2
     exit 1
   fi
 
@@ -505,64 +528,46 @@ function delete-switch()
   $NB_CMD ls-del $name  >/dev/null  2>&1 
   $NB_CMD lr-del $router >/dev/null  2>&1
   $NB_CMD dhcp-options-del $dhcpid >/dev/null  2>&1  
+  
+  #ovs-vsctl remove Open_vSwitch . external_ids ovn-bridge-mappings
 }
 
 function bind-fip()
 {
   switch=$(echo $* | awk -F"--swName" '{print$2}' | awk '{print$1}')
+  os=$(echo $* | awk -F"--outSwName" '{print$2}' | awk '{print$1}')
   bridge=$(echo $* | awk -F"--bridge" '{print$2}' | awk '{print$1}')
   vmmac=$(echo $* | awk -F"--vmmac" '{print$2}' | awk '{print$1}')
   fip=$(echo $* | awk -F"--fip" '{print$2}' | awk '{print$1}')
  
-  if [[ -z $1 || -z $switch || -z $bridge || -z $vmmac || -z $fip || -z $(echo $fip | grep "/") || $2 == "--help" ]]
+  if [[ -z $1 || -z $switch || -z $os || -z $vmmac || -z $fip || -z $(echo $fip | grep "/") || $2 == "--help" ]]
   then
     cmddesc
-    echo -e "--swName  \tswitch name" >&2
-    echo -e "--bridge  \tbridge" >&2
-    echo -e "--vmmac   \tvm mac" >&2
-    echo -e "--fip     \tflating ip and mask, for example, 192.168.1.1/24" >&2
+    echo -e "--swName    \tswitch name" >&2
+    echo -e "--outSwName \tout switch name" >&2
+    echo -e "--vmmac     \tvm mac" >&2
+    echo -e "--fip       \tflating ip and mask, for example, 192.168.1.1/24" >&2
     exit 1
   fi
 
   checkOVSStatus
 
-  res=$(ovs-vsctl list-br | grep $bridge)
-  if [[ -z $res ]]
-  then
-    echo -e "cannot find bridge" >&2
-    exit 1
-  fi
-  
   vmip=$($NB_CMD list logical_switch_port  | grep "$vmmac" | awk -F"\"" '{print$2}' | awk '{print$2}')
 
   router=$switch"-router"
   fport="public-"${vmmac//:/}"-port"
   ip=$(echo $fip | awk -F"/" '{print$1}')
-  rmk=$(echo $fip | awk -F"/" '{print$2}')
-  #pip=$(echo $ip | awk -F"." '{print$1"."$2"."$3}')".250"
+  
   imac=$(printf '00:60:2F:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
   
-  #$NB_CMD lrp-add $router $fport  $imac $pip"/"$rmk
-  $NB_CMD lrp-add $router $fport  $imac $ip"/"$rmk
-  $NB_CMD lrp-set-gateway-chassis $fport $($SB_CMD show | grep -B 3 "$THISIP" | grep Chassis | awk -F"\"" '{print$2}')
-
-  pswn="public-"${vmmac//:/}"-"$(hostname)
+  $NB_CMD lrp-add $router $fport  $imac $fip
   
-  $NB_CMD ls-add $pswn
-  $NB_CMD lsp-add $pswn "from-"$fport
+  $NB_CMD lsp-add $os "from-"$fport
   $NB_CMD lsp-set-type "from-"$fport router
   $NB_CMD lsp-set-addresses "from-"$fport $imac
   $NB_CMD lsp-set-options "from-"$fport router-port=$fport
-  
-  $NB_CMD lsp-add $pswn "to-"$pswn"-localnet"
-  $NB_CMD lsp-set-addresses "to-"$pswn"-localnet" unknown
-  $NB_CMD lsp-set-type "to-"$pswn"-localnet" localnet
-  $NB_CMD lsp-set-options "to-"$pswn"-localnet" network_name=$pswn
-  
-  ovs-vsctl set Open_vSwitch . external-ids:ovn-bridge-mappings=$pswn:$bridge
 
   $NB_CMD lr-nat-add $router dnat_and_snat $ip $vmip
-  #$NB_CMD lr-nat-add $router dnat_and_snat $pip $vmip 
   
 }
 
@@ -582,16 +587,11 @@ function unbind-fip()
   fi
 
   checkOVSStatus
-  
-  pswn="public-"${vmmac//:/}"-"$(hostname)
-  $NB_CMD ls-del $pswn
 
   router=$switch"-router"
   fport="public-"${vmmac//:/}"-port"
   $NB_CMD lrp-del $fport
-  #pip=$(echo $ip | awk -F"." '{print$1"."$2"."$3}')".250"
   $NB_CMD lr-nat-del $router dnat_and_snat $fip
-  #$NB_CMD lr-nat-del $router dnat_and_snat $pip
 }
 
 ###########################################################
