Update ovn-emulator

diff --git a/src/ovn-emulator b/src/ovn-emulator
--- a/src/ovn-emulator
+++ b/src/ovn-emulator
@@ -392,6 +392,127 @@ function create-switch()
   imtu=$(echo $* | awk -F"--mtu" '{print$2}' | awk '{print$1}')
   excl=$(echo $* | awk -F"--excludeIPs" '{print$2}' | awk '{print$1}')
   dnss=$(echo $* | awk -F"--dnsServer" '{print$2}' | awk '{print$1}')
+  ipv4=$(echo $* | awk -F"--ipv4" '{print$2}' | awk '{print$1}')
+  
+  if [[ -z $1 || -z $name || -z $subn || $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--name       \tswitch name" >&2
+    echo -e "--subnet     \tIP range. for example, 192.168.1.0/24"  >&2
+    echo -e "--gateway    \tgateway.  for example, 192.168.1.1"  >&2
+    echo -e "--dhcp       \tdhcp"  >&2
+    echo -e "--mtu        \toptinal, mtu.  for example, 1480"  >&2
+    echo -e "--bridge     \toptinal,bridge"  >&2
+    echo -e "--vlanId     \toptinal,vlanId"  >&2
+    echo -e "--excludeIPs \toptinal, excludeIPs.  192.168.1.1,192.168.1.10..192.168.1.100"  >&2
+    echo -e "--dnsServer  \toptinal, dnsServer.  192.168.1.1"  >&2
+    echo -e "--ipv4       \toptinal, true or false"  >&2
+    exit 1
+  fi
+
+  sid=$($NB_CMD ls-list | grep "($name)" | awk '{print$1}')
+  if [[ -n $sid ]]
+  then
+    echo "cannot connect the master or the switch name exists" >&2
+    exit 1
+  fi
+ 
+  $NB_CMD ls-add $name
+
+  if [[ -n $excl ]]
+  then
+    nexcl=$(echo ${excl//,/ })
+    $NB_CMD set Logical_Switch $name other_config:exclude_ips="$nexcl"
+  fi
+ 
+  if [[ -n $subn ]]
+  then
+  
+    mtu="1500"
+    if [[ -n $imtu ]]
+    then
+      mtu=$imtu
+    fi
+ 
+    if [[ -n $dhcp ]]
+    then
+      router=$name"-router"
+      rport=$name"-router-port"
+      
+      if [[ $ipv4 == "false" ]]
+      then
+        rmac=$(printf 'fd15:4ba5:5a2b:1008:%02X%02X:%02X%02X:%02X%02X:%02X%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
+      else
+        rmac=$(printf '00:60:2F:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
+      fi
+ 
+      $NB_CMD lr-add $router
+      $NB_CMD set Logical_router $router options:chassis=$($SB_CMD show | grep -B 3 "$THISIP" | grep Chassis | awk -F"\"" '{print$2}')
+	  
+      rmk=$(echo $subn | awk -F"/" '{print$2}')
+      $NB_CMD lrp-add $router $rport $rmac $dhcp"/"$rmk
+  
+      mport="mapping-to-"$router
+      $NB_CMD lsp-add $name $mport
+      $NB_CMD lsp-set-type $mport router
+      $NB_CMD lsp-set-addresses $mport $rmac
+      $NB_CMD lsp-set-options $mport router-port=$rport
+       
+      if [[ -n $bridge ]]
+      then 
+        sport='to-'$rport'-'$(hostname)'-localnet'
+        $NB_CMD lsp-add $name $sport
+        $NB_CMD lsp-set-addresses $sport unknown
+        $NB_CMD lsp-set-type $sport localnet
+        pswn=${rmac//:/}"-"$sport
+      
+        $NB_CMD lsp-set-options $sport network_name=$pswn
+ 
+        eids=$(ovs-vsctl list Open_vSwitch | grep external_ids | awk -F"ovn-bridge-mappings=\"" '{print$2}' | awk -F"\"" '{print$1}')
+   
+        if [[ -n $vlanId ]]
+        then
+          $NB_CMD set Logical_Switch_Port $sport tag=$vlanId
+        fi
+
+        if [[ -z $eids ]] 
+        then
+          ovs-vsctl set Open_vSwitch . external-ids:ovn-bridge-mappings=$pswn:$bridge
+        else
+          ovs-vsctl set Open_vSwitch . external-ids:ovn-bridge-mappings=$pswn:$bridge,$eids
+        fi
+      fi
+
+      if [[ -z $dnss ]]
+      then
+        did=$($NB_CMD create DHCP_Options cidr=$subn options="\"server_id\"=\"$dhcp\" \"server_mac\"=\"$rmac\" \"lease_time\"=\"3600\" \"router\"=\"$gway\" \"mtu\"=\"$mtu\"")
+      else
+        did=$($NB_CMD create DHCP_Options cidr=$subn options="\"server_id\"=\"$dhcp\" \"server_mac\"=\"$rmac\" \"lease_time\"=\"3600\" \"router\"=\"$gway\" \"mtu\"=\"$mtu\" \"dns_server\"=\"$dnss\"")
+      fi
+
+      if [[ $ipv4 == "false" ]]
+      then
+        $NB_CMD lsp-add $name "dhcpv6id-$name-"$did
+      else
+        $NB_CMD lsp-add $name "dhcpv4id-$name-"$did
+      fi
+      
+      fi
+  fi
+
+}
+
+function create-switch6()
+{
+  name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
+  subn=$(echo $* | awk -F"--subnet" '{print$2}' | awk '{print$1}')
+  bridge=$(echo $* | awk -F"--bridge" '{print$2}' | awk '{print$1}')
+  vlanId=$(echo $* | awk -F"--vlanId" '{print$2}' | awk '{print$1}')
+  gway=$(echo $* | awk -F"--gateway" '{print$2}' | awk '{print$1}')
+  dhcp=$(echo $* | awk -F"--dhcp" '{print$2}' | awk '{print$1}')
+  imtu=$(echo $* | awk -F"--mtu" '{print$2}' | awk '{print$1}')
+  excl=$(echo $* | awk -F"--excludeIPs" '{print$2}' | awk '{print$1}')
+  dnss=$(echo $* | awk -F"--dnsServer" '{print$2}' | awk '{print$1}')
   
   if [[ -z $1 || -z $name || -z $subn || $2 == "--help" ]]
   then
@@ -498,6 +619,89 @@ function modify-switch()
   imtu=$(echo $* | awk -F"--mtu" '{print$2}' | awk '{print$1}')
   dnss=$(echo $* | awk -F"--dnsServer" '{print$2}' | awk '{print$1}')
   vlanId=$(echo $* | awk -F"--vlanId" '{print$2}' | awk '{print$1}')
+  ipv4=$(echo $* | awk -F"--ipv4" '{print$2}' | awk '{print$1}')
+
+  if [[ -z $1 || -z $name || $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--name       \tswitch name" >&2
+    echo -e "--vlanId     \tvlanId" >&2
+    echo -e "--gateway    \toptinal, gateway.  for example, 192.168.1.1"  >&2
+    echo -e "--dhcp       \toptinal, dhcp.  for example, 192.168.1.1"  >&2
+    echo -e "--mtu        \toptinal, mtu.  for example, 1480"  >&2
+    echo -e "--dnsServer  \toptinal, dns server"  >&2
+    echo -e "--ipv4       \toptinal, true or false"  >&2
+    exit 1
+  fi
+  
+  if [[ $ipv4 == "fasle" ]]
+  then
+    dhcpid=$($NB_CMD show $name | grep "dhcpv6id-$name-" | awk -F "dhcpv6id-$name-" '{print$2}') 
+  else
+    dhcpid=$($NB_CMD show $name | grep "dhcpv4id-$name-" | awk -F "dhcpv4id-$name-" '{print$2}') 
+  fi
+ 
+  thisdhcp=$($NB_CMD dhcp-options-get-options $dhcpid | grep "server_id" | awk -F"=" '{print$2}')
+  thisgway=$($NB_CMD dhcp-options-get-options $dhcpid | grep "router" | awk -F"=" '{print$2}')
+  rmac=$($NB_CMD dhcp-options-get-options $dhcpid | grep "server_mac" | awk -F"=" '{print$2}')
+  thismtu=$($NB_CMD dhcp-options-get-options $dhcpid | grep "mtu" | awk -F"=" '{print$2}')
+  thisdns=$($NB_CMD dhcp-options-get-options $dhcpid | grep "dns_server" | awk -F"=" '{print$2}')
+
+  if [[ -n $dhcp ]]
+  then
+    thisdhcp=$dhcp
+  fi
+
+  if [[ -n $gway ]]
+  then
+    thisgway=$gway
+  fi
+
+  if [[ -n $imtu ]]
+  then
+    thismtu=$imtu
+  fi
+
+  if [[ -n $dnss  ]]
+  then
+    thisdns=$dnss
+  fi
+
+  cmd="$dhcpid server_mac=$rmac lease_time=3600 mtu=$thismtu"
+  if [[ -n $thisdhcp ]]
+  then
+    cmd=$cmd" server_id=$thisdhcp"
+  fi
+
+  if [[ -n $thisgway ]]
+  then
+    cmd=$cmd" router=$thisgway"
+  fi
+
+  if [[ -n $thisdns ]]
+  then
+    cmd=$cmd" dns_server=$thisdns"
+  fi
+
+  $($NB_CMD dhcp-options-set-options $cmd)
+
+  if [[ -n $vlanId ]]
+  then
+    rport=$name"-router-port"
+    sport='to-'$rport'-'$(hostname)'-localnet'
+    $NB_CMD set Logical_Switch_Port $sport tag=$vlanId 
+  fi
+
+}
+
+function modify-switch6()
+{
+  name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
+  gway=$(echo $* | awk -F"--gateway" '{print$2}' | awk '{print$1}')
+  dhcp=$(echo $* | awk -F"--dhcp" '{print$2}' | awk '{print$1}')
+  imtu=$(echo $* | awk -F"--mtu" '{print$2}' | awk '{print$1}')
+  dnss=$(echo $* | awk -F"--dnsServer" '{print$2}' | awk '{print$1}')
+  vlanId=$(echo $* | awk -F"--vlanId" '{print$2}' | awk '{print$1}')
 
   if [[ -z $1 || -z $name || $2 == "--help" ]]
   then
@@ -567,7 +771,104 @@ function modify-switch()
 }
 
 # ovs-vsctl remove Open_vSwitch . external_ids ovn-bridge-mappings
+# ovs-vsctl remove Open_vSwitch . external_ids ovn-bridge-mappings
 function delete-switch()
+{
+  name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
+  bridge=$(echo $* | awk -F"--bridge" '{print$2}' | awk '{print$1}')
+  ipv4=$(echo $* | awk -F"--ipv4" '{print$2}' | awk '{print$1}')
+  
+  if [[ -z $1 || -z $name || $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--name    \tswitch name" >&2
+    echo -e "--bridge  \tbridge name" >&2
+    echo -e "--ipv4    \ttrue of false" >&2
+    exit 1
+  fi
+
+  ## check
+  checkOVSStatus
+  
+  sid=$($NB_CMD ls-list | grep "($name)" | awk '{print$1}')
+  if [[ -z $sid ]]
+  then
+    echo "cannot connect the master or the switch name does not exist" >&2
+    exit 1
+  fi
+
+  ## del db
+  router=$name"-router"
+  if [[ -n $bridge ]]
+  then
+    ppnn=$($NB_CMD show | grep -A 1 $router"-port" | grep mac | awk -F"\"" '{print$2}')
+    ovsn=${ppnn//:/}"-to-"$router"-port-"$(hostname)"-localnet:"$bridge
+    full=$(ovs-vsctl list Open_vSwitch | grep external_ids | awk -F"ovn-bridge-mappings=\""  '{print$2}' | awk -F"\"" '{print$1}')
+
+    remain=${full//$ovsn/}
+    if [[ -n ${remain:1:2} ]]
+    then
+      ovs-vsctl set Open_vSwitch . external_ids:ovn-bridge-mappings=${remain:1}
+    else
+      ovs-vsctl remove Open_vSwitch . external_ids ovn-bridge-mappings
+    fi
+  fi
+  
+  ## delete
+  if [[ $ipv4 == "fasle" ]]
+  then
+    dhcpid=$($NB_CMD show $name | grep "dhcpv6id-$name-" | awk -F"dhcpv6id-$name-" '{print$2}')
+  else
+    dhcpid=$($NB_CMD show $name | grep "dhcpv4id-$name-" | awk -F"dhcpv4id-$name-" '{print$2}')
+  fi
+  $NB_CMD ls-del $name  >/dev/null  2>&1 
+  $NB_CMD lr-del $router >/dev/null  2>&1
+  $NB_CMD dhcp-options-del $dhcpid >/dev/null  2>&1  
+ 
+}
+
+function bind-fip()
+{
+  switch=$(echo $* | awk -F"--swName" '{print$2}' | awk '{print$1}')
+  os=$(echo $* | awk -F"--outSwName" '{print$2}' | awk '{print$1}')
+  bridge=$(echo $* | awk -F"--bridge" '{print$2}' | awk '{print$1}')
+  vmmac=$(echo $* | awk -F"--vmmac" '{print$2}' | awk '{print$1}')
+  fip=$(echo $* | awk -F"--fip" '{print$2}' | awk '{print$1}')
+ 
+  if [[ -z $1 || -z $switch || -z $os || -z $vmmac || -z $fip || -z $(echo $fip | grep "/") || $2 == "--help" ]]
+  then
+    cmddesc
+    echo -e "--swName    \tswitch name" >&2
+    echo -e "--outSwName \tout switch name" >&2
+    echo -e "--vmmac     \tvm mac" >&2
+    echo -e "--fip       \tflating ip and mask, for example, 192.168.1.1/24" >&2
+    exit 1
+  fi
+
+  checkOVSStatus
+
+  vmip=$($NB_CMD list logical_switch_port  | grep "$vmmac" | awk -F"\"" '{print$2}' | awk '{print$2}')
+
+  router=$switch"-router"
+  fport="public-"${vmmac//:/}"-port"
+  ip=$(echo $fip | awk -F"/" '{print$1}')
+  
+  imac=$(printf '00:60:2F:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
+  
+  $NB_CMD lrp-add $router $fport  $imac $fip
+  
+  $NB_CMD lsp-add $os "from-"$fport
+  $NB_CMD lsp-set-type "from-"$fport router
+  $NB_CMD lsp-set-addresses "from-"$fport $imac
+  $NB_CMD lsp-set-options "from-"$fport router-port=$fport
+
+  #$NB_CMD lr-nat-add $router dnat_and_snat $ip $vmip
+  $NB_CMD lr-nat-add $router snat $ip $vmip
+  $NB_CMD lr-nat-add $router dnat $ip $vmip
+  
+}
+
+function delete-switch6()
 {
   name=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
   bridge=$(echo $* | awk -F"--bridge" '{print$2}' | awk '{print$1}')
